//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMarathon.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMarathon.App.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A marathon course is unique for several reasons including altimetry..
        /// </summary>
        public static string About_Altimetry_P1 {
            get {
                return ResourceManager.GetString("About_Altimetry_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That means we can create an elevation profile of our marathon classifying each mile and adding or removing some seconds to our goal pace as shown below:.
        /// </summary>
        public static string About_Altimetry_P2 {
            get {
                return ResourceManager.GetString("About_Altimetry_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downhill = 10 seconds faster per mile.
        /// </summary>
        public static string About_Altimetry_P3 {
            get {
                return ResourceManager.GetString("About_Altimetry_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat = keep goal pace.
        /// </summary>
        public static string About_Altimetry_P4 {
            get {
                return ResourceManager.GetString("About_Altimetry_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uphill = 10 seconds slower per mile.
        /// </summary>
        public static string About_Altimetry_P5 {
            get {
                return ResourceManager.GetString("About_Altimetry_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step One: Course Altimetry.
        /// </summary>
        public static string About_Altimetry_Title {
            get {
                return ResourceManager.GetString("About_Altimetry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  — Given your goal pace of, say 9:00/miles, you purposely start of slower by about 15 seconds per mile. Then you start to bring the pace down such that by mile five, you are running at or just under your goal pace. It sounds crazy, for sure, but it means you aren&apos;t running too hard, or wasting energy trying to weave around the competition. You are just in your zone, slowly building up your pace to where you&apos;ll want it to sit all day..
        /// </summary>
        public static string About_Approach_P1 {
            get {
                return ResourceManager.GetString("About_Approach_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Smart (Miles 0 to 5).
        /// </summary>
        public static string About_Approach_P1_Title {
            get {
                return ResourceManager.GetString("About_Approach_P1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  — The bulk of your race is spent running just under our goal pace. For our 9:00 runner, this means miles in the 8:55 range. The purpose here is to be consistent but to slowly chip away at the timing surplus that our early conservative pacing created. By the time we reach the end of this section of our day, you should be right on target for your goal time but in a much better place..
        /// </summary>
        public static string About_Approach_P2 {
            get {
                return ResourceManager.GetString("About_Approach_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run to the Line (Miles 6 to 20).
        /// </summary>
        public static string About_Approach_P2_Title {
            get {
                return ResourceManager.GetString("About_Approach_P2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Line (Aka the “wall”) is the part of your race day where your body begins to push back. In general this happens between miles 18 and 22 on race day, depending on the course, your pacing, your fitness, etc. Of course, most runners go out fast putting time in to “the bank” for when they slow down — I am here to tell you there is no such bank, and that time you saved will mostly likely be nowhere near sufficient to staunch the bleeding at the end of your day..
        /// </summary>
        public static string About_Approach_P3 {
            get {
                return ResourceManager.GetString("About_Approach_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until you hit the “line” you aren’t racing, you are running. You ignore the other runners and do your best to flatten out the course through smart pacing. Nutritionally you are fueling in anticipation of the last six miles..
        /// </summary>
        public static string About_Approach_P4 {
            get {
                return ResourceManager.GetString("About_Approach_P4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last six miles on race day are were dreams are made (or broken). Inside Marathon Nation we don’t dread the end of the race; it’s where our day begins. If you have paced yourself properly, you’ll just be starting to pass other runners as everyone around you is slowing down. This is not only a judicious application of your fitness, it’s a powerful mental strategy that helps you stay focused just as your body is trying to check out..
        /// </summary>
        public static string About_Approach_P5 {
            get {
                return ResourceManager.GetString("About_Approach_P5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race to the Finish (Miles 21 to Finish).
        /// </summary>
        public static string About_Approach_P5_Title {
            get {
                return ResourceManager.GetString("About_Approach_P5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In summary, the basic Marathon Nation Pacing approach is:.
        /// </summary>
        public static string About_Approach_P6 {
            get {
                return ResourceManager.GetString("About_Approach_P6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give away 15 seconds per mile for first six miles..
        /// </summary>
        public static string About_Approach_P7 {
            get {
                return ResourceManager.GetString("About_Approach_P7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain back 5 seconds per mile from miles 6 through 20..
        /// </summary>
        public static string About_Approach_P8 {
            get {
                return ResourceManager.GetString("About_Approach_P8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 10k is on pace..
        /// </summary>
        public static string About_Approach_P9 {
            get {
                return ResourceManager.GetString("About_Approach_P9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Two: The Marathon Nation Race Approach.
        /// </summary>
        public static string About_Approach_Title {
            get {
                return ResourceManager.GetString("About_Approach_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this web site is help people to run a smart marathon following a race strategy based on course altimetry and running negative splits allowing save energy for last miles where most of marathoners slowed significantly..
        /// </summary>
        public static string About_P1 {
            get {
                return ResourceManager.GetString("About_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having said that let&apos;s describe the steps followed to calculate your splits for a smart marathon:.
        /// </summary>
        public static string About_P2 {
            get {
                return ResourceManager.GetString("About_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT SMART MARATHON.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me for any comment or question you could have or request to add a marathon elevation profile in the list..
        /// </summary>
        public static string ContactMe_P1 {
            get {
                return ResourceManager.GetString("ContactMe_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also any experience running your marathons guided by Smart Marathon is welcome to be included in a future section..
        /// </summary>
        public static string ContactMe_P2 {
            get {
                return ResourceManager.GetString("ContactMe_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find helpful this site please feel free to make any donation and contribute to pay hosting charges, make improvements and develop future sections:.
        /// </summary>
        public static string ContactMe_P3 {
            get {
                return ResourceManager.GetString("ContactMe_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT ME.
        /// </summary>
        public static string ContactMe_Title {
            get {
                return ResourceManager.GetString("ContactMe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10K.
        /// </summary>
        public static string Distance_10K {
            get {
                return ResourceManager.GetString("Distance_10K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30K.
        /// </summary>
        public static string Distance_30K {
            get {
                return ResourceManager.GetString("Distance_30K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5K.
        /// </summary>
        public static string Distance_5K {
            get {
                return ResourceManager.GetString("Distance_5K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Marathon.
        /// </summary>
        public static string Distance_HalfMarathon {
            get {
                return ResourceManager.GetString("Distance_HalfMarathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathon.
        /// </summary>
        public static string Distance_Marathon {
            get {
                return ResourceManager.GetString("Distance_Marathon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Distance_Other {
            get {
                return ResourceManager.GetString("Distance_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALCULATE.
        /// </summary>
        public static string Label_Calculate {
            get {
                return ResourceManager.GetString("Label_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTANCE.
        /// </summary>
        public static string Label_Distance {
            get {
                return ResourceManager.GetString("Label_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENT.
        /// </summary>
        public static string Label_Event {
            get {
                return ResourceManager.GetString("Label_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH TIME.
        /// </summary>
        public static string Label_FinishTime {
            get {
                return ResourceManager.GetString("Label_FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL PACE.
        /// </summary>
        public static string Label_GoalPace {
            get {
                return ResourceManager.GetString("Label_GoalPace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOAL TIME.
        /// </summary>
        public static string Label_GoalTime {
            get {
                return ResourceManager.GetString("Label_GoalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your goal time and classify each split according race altimetry.
        /// </summary>
        public static string Label_Instructions {
            get {
                return ResourceManager.GetString("Label_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Label_Or {
            get {
                return ResourceManager.GetString("Label_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACE.
        /// </summary>
        public static string Label_Pace {
            get {
                return ResourceManager.GetString("Label_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOUR DISTANCE.
        /// </summary>
        public static string Label_RealDistance {
            get {
                return ResourceManager.GetString("Label_RealDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIME.
        /// </summary>
        public static string Label_Time {
            get {
                return ResourceManager.GetString("Label_Time", resourceCulture);
            }
        }
    }
}
